### Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$



In [4]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'\nСобственные значения:\n{w}')
print(f'\nСобственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]

Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]



### Дан оператор поворота на 180 градусов, задаваемый матрицей 

$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$

Показать, что __любой__ вектор является для него собственным.

In [32]:
import numpy as np

a = np.array([[-1, 0], [0, -1]])
x_1 = np.array([[-1], [0]])
x_2 = np.array([[-1], [1]])

print(f'Вектор #1: \n{x_1}')
print(f'Скалярное произведение #1: \n{np.dot(a, x_1)}')
print(f'lambda=-1\n')
print(f'Вектор #2: \n{x_2}')
print(f'Скалярное произведение #2: \n{np.dot(a, x_2)}')
print(f'lambda=-1\n')

Вектор #1: 
[[-1]
 [ 0]]
Скалярное произведение #1: 
[[1]
 [0]]
lambda=-1

Вектор #2: 
[[-1]
 [ 1]]
Скалярное произведение #2: 
[[ 1]
 [-1]]
lambda=-1



### Пусть линейный оператор задан матрицей

$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

In [18]:
import numpy as np

a = np.array([[1, 1], [-1, 3]])
x = np.array([[1], [1]])
print(f'Скалярное произведение: \n{np.dot(a, x)}')
print(f'\nlambda=2\n')
print(f'Вектор x является собственным линейного оператора A')

Скалярное произведение: 
[[2]
 [2]]

lambda=2

Вектор x является собственным линейного оператора A
