### Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

   а) произведения матриц определены; размерность (4,2)
    
   б) произведения матриц не определены
    
   в) произведения матриц не определены
    
   г) произведения матриц определены; размерность (4,4)

### Найти сумму и произведение матриц 
$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [23]:
import numpy as np

A = np.array([(1, -2),(3, 0)])
B = np.array([(4, -1),(0, 5)])

print(f'Сумма:\n{A + B}')
print(f'\nПроизведение:\n{A * B}')

Сумма:
[[ 5 -3]
 [ 3  5]]

Произведение:
[[4 2]
 [0 0]]



### Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию 
$3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [24]:
import numpy as np

A = np.array([(1, 7),(3, -6)])
B = np.array([(0, 5),(2, -1)])
C = np.array([(2, -4),(1, 1)])

result = 3*A - 2*B + 4*C
print(result)

[[ 11  -5]
 [  9 -12]]


### Дана матрица 
$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

### *Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [83]:
import numpy as np

def dot(A, B):
    C = []
    for k in range(0, A.shape[0]):
        a = A[k, :]
        C_ = []
        for j in range(0, B.shape[0]):
            b = B[:, j]
            c = 0
            for i in zip(a, b):
                c += i[0] * i[1]
            C_.append(c)
        C.append(C_)
    
    return C

A = np.array([(1, 7, 3), (3, 4, 5), (3, -6, 5)])
B = np.array([(0, 5, 2), (6, 4, 5), (2, -1, 6)])
print(dot(A, B))

print(f'\nПроверка:\n{np.dot(A, B)}')

[[48, 30, 55], [34, 26, 56], [-26, -14, 6]]

Проверка:
[[ 48  30  55]
 [ 34  26  56]
 [-26 -14   6]]
